routes/web.php
<?php

use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::post('animals/foundAnimal', 'AnimalController@foundTheAnimal')->name('animals.foundAnimal');
Route::get('/register', 'UserController@register')->name('register');
Route::post('register/store', 'UserController@storeRegister')->name('storeRegister');

Route::group(['middleware' => 'auth'], function () {
	
	Route::resource('users', 'UserController');

    Route::resource('animals', 'AnimalController');
    Route::get('animals/showFinders/{animal}', 'AnimalController@showFinders')->name('animals.showFinders');
    
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'email', 
        'telefone',
        'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get the animals for the user.
     */
    public function animals()
    {
        return $this->hasMany('App\Animal');
    }

    /**
     * Get the role that owns the user.
     */
    public function roles()
    {
        return $this->belongsToMany('App\Role', 'model_has_roles', 'model_id', 'role_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use App\Permission;
use App\Role;
use App\Schooling;
use App\Services\UserService;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Servico de Usuários
     * @var \App\Services\UserService
     */
    protected $userService;

    /**
     * Método construtor
     *
     * @param \App\Services\UserService  $userService  O servico de usuários
     */
    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }
    
    public function AuthRouteAPI(Request $request){
        return $request->user();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = $this->userService->findAllUsers();

        return view('user.index', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = $this->userService->findAllDepartments();
        $roles = $this->userService->findAllRoles();
        $user = new User();

        return view('user.new')->with(compact('departments', 'roles', 'user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request = $this->userService->fillRequestUser($request);

        $user = $this->userService->storeUser($request);

        // Create the user
        if ( $user ) {

            flash('Usuário criado com sucesso.');

        } else {
            flash()->error('Não foi possível criar o usuário. Contate o administrador.');
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $departments = $this->userService->findAllDepartments();
        $roles = $this->userService->findAllRoles();

        return view('user.edit', compact('user', 'roles', 'departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request = $this->userService->fillRequestUser($request);

        $user = $this->userService->updateUser($request, $id);

        if ($user) {
            if ($request->has('roles')) {
                $this->syncPermissions($request, $user);
            }

            flash('Usuário alterado com sucesso.');

        } else {
            flash()->error('Não foi possível alterar o usuário. Contate o administrador.');
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Sync roles and permissions
     *
     * @param Request $request
     * @param $user
     * @return string
     */
    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);

        return $user;
    }

    /**
     * { function_description }
     *
     * @return     <type>  ( description_of_the_return_value )
     */
    public function register()
    {
        return view('auth.register');
    }

    /**
     * Stores a register.
     *
     * @param      \Illuminate\Http\Request  $request  The request
     *
     * @return     <type>                    ( description_of_the_return_value )
     */
    public function storeRegister(Request $request)
    {
        $request = $this->userService->fillRequestUser($request);

        $user = $this->userService->storeUser($request);

        // Create the user
        if ( $user ) {

            flash('Usuário criado com sucesso.');
            

            return redirect(url('/login'));

        } else {
            flash()->error('Não foi possível criar o usuário. Contate o administrador.');
        }

        return redirect()->route('users.index');
    }
}

resources/views/user/_form.blade.php
<div class="form-body">
    <div class="alert alert-danger display-hide">
    <button class="close" data-close="alert"></button>
    Você tem alguns erros de formulário. Por favor, verifique abaixo.
    </div>
    <div class="alert alert-success display-hide">
    <button class="close" data-close="alert"></button> Sua validação de formulário foi bem sucedida! </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Nome
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <div class="input-icon right">
                    <i class="fa fa-user"></i>
                    <input name="name" type="text" class="form-control" placeholder="Enter name" value="{{ old('name') ? old('name') : $user->name }}"> </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Email
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <div class="input-icon right">
                    <i class="fa fa-envelope"></i>
                    <input name="email" type="text" class="form-control" placeholder="Email Address" value="{{ old('email') ? old('email') : $user->email }}"> </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">CPF
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <div class="input-icon right">
                    <i class="fa fa-user"></i>
                    <input name="cpf" type="text" class="form-control cpf-mask" placeholder="Enter CPF" value="{{ old('cpf') ? old('cpf') : $user->cpf }}"> </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3">Data Nascimento</label>
            <div class="col-md-4">
                <div class="input-group input-icon col-md-4">
                <i class="fa fa-birthday-cake"></i>
                    <input name="birth_date" type="text" size="16" class="form-control form-control-inline input-medium date-mask" value="{{ old('birth_date') ? old('birth_date') : $user->birth_date != null ? $user->birth_date->format('d/m/Y') : "" }}">
                    <span class="input-group-btn">
                        <button class="btn default date-set" type="button">
                            <i class="fa fa-calendar"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3">Data Admissão</label>
            <div class="col-md-4">
                <div class="input-group input-icon col-md-4">
                <i class="fa fa-thumb-tack"></i>
                    <input name="adm_date" type="text" size="16" class="form-control form-control-inline input-medium date-mask" value="{{ old('adm_date') ? old('adm_date') : $user->adm_date != null ? $user->adm_date->format('d/m/Y') : "" }}">
                    <span class="input-group-btn">
                        <button class="btn default date-set" type="button">
                            <i class="fa fa-calendar"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="single-prepend-text" class="control-label col-md-3">Departamento
            <span class="required"> * </span></label>
            <div  class="col-md-5">
            <div class="input-group select2-bootstrap-prepend">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" data-select2-open="single-prepend-text">
                        <span class="fa fa-home"></span>
                    </button>
                </span>
                <input type="hidden" name="department_id">
                <select id="departments" name="department_id" class="form-control select2 required">
                    <option value=""></option>
                    @foreach($departments as $d)
                        <option {{$user->department_id === $d->id ? "selected" : ""}} value="{{ $d->id }}">{{ $d->description }}</option>
                    @endforeach    
                </select>
            </div>
            </div>
        </div>
        <div class="form-group">
            <label for="single-prepend-text" class="control-label col-md-3">Cargo
            <span class="required"> * </span></label>
            <div  class="col-md-5">
            <div class="input-group select2-bootstrap-prepend">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" data-select2-open="single-prepend-text">
                        <span class="fa fa-black-tie"></span>
                    </button>
                </span>
                <input type="hidden" name="roles">
                <select id="roles" class="form-control select2 required">
                    <option value=""></option>
                    @foreach($roles as $r)
                        <option value="{{ $r->id }}">{{ $r->name }}</option>
                    @endforeach    
                </select>
            </div>
                <span class="help-inline">O cargo define as permissões do usuário dentro do sistema.</span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Senha
            <span class="required"> * </span></label>
            <div class="col-md-5" data-toggle="popover" data-placement="top" data-content="Deve ter no mínimo 6 caracteres.">
                <div class="input-icon right">
                    <i class="fa fa-lock"></i>
                    <input name="password" id="password" type="password" class="form-control" placeholder="Password"> 
                    <span class="help-inline"> Deve ter no mínimo 6 caracteres. </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Confirmar Senha
            <span class="required"> * </span></label>
            <div class="col-md-5" data-toggle="popover" data-placement="top" data-content="Deve ter no mínimo 6 caracteres.">
                <div class="input-icon right">
                    <i class="fa fa-lock"></i>
                    <input name="password_confirm" name="password_confirm" type="password" class="form-control" placeholder="Password">
                </div>
            </div>
        </div>
</div>
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-3 col-md-9">
            <button type="submit" class="btn btn-success">Salvar</button>
            <a class="btn default" href="{{ route('users.index') }}">Cancelar</a>
        </div>
    </div>
</div>

resources/views/user/edit.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
        <a href="{{ action('UserController@index') }}" class="nav-link nav-toggle">
            <span class="title">Usuários</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Editar
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Usuários
        <small>Editar</small>
    </h1>

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer bold"></i>
                    <span class="caption-subject bold uppercase">Editar Usuário</span>
                    <span class="caption-helper">formulário para edição de usuário</span>
                </div>
                <div class="actions">
                    
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ route('users.update', $user->id) }}" METHOD="POST" id="formUser" class="form-horizontal" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    @include('user._form')
                </form>
                <!-- END FORM-->
            </div>
        </div>

    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')
    <script type="text/javascript">
        // $(document).ready(function () {
        //     $("#formUser").submit(function(e) {
        //         e.preventDefault();
        //         $('[name="schooling_id"]').val(($("#schoolings").val()));
        //         $('[name="department_id"]').val(($("#departments").val()));
        //         $('[name="roles"]').val(($("#roles").val()));
        //     });
        // });

    </script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.default')

@section('title')
    Usuários    
@endsection

@section('css-plugins')
        <!--Datatable-->
        <link href="{{ asset("assets/global/plugins/datatables/datatables.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
            Usuários
	</li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Usuários
        <small>Index</small>
    </h1>

	<a class="btn blue-sharp btn-outline sbold pull-right" href="{{ route('users.create') }}"><i class="fa fa-user-plus"></i> Novo Usuário</a>
	<div style="margin:0; padding:0; height:50px;">&nbsp;</div>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">Usuários</b></span>
                    </div>
                    <div class="tools"> </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_1">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Email</th>
                                <th>CPF</th>
                                <th>Departamento</th>
                                <th>Cargo</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                    <tbody>
                        @foreach($result as $r)
                            <tr>
                                <td>{{$r->name}}</td>
                                <td>{{$r->email}}</td>
                                <td>{{$r->cpf}}</td>
                                <td>{{$r->department->description}}</td>
                                <td>{{isset($r->roles->first()->name) ? $r->roles->first()->name : "" }}</td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Ações
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-left" role="menu">
                                            <li>
                                                <a href="{{ route('users.edit', $r->id) }}">
                                                    <i class="fa fa-edit"></i> Editar </a>
                                            </li>
                                            <li>
                                            <form role="form" action="{{ action('UserController@destroy', $r->id) }}" METHOD="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}<button type="submit">Desativar</button>
                                            </form>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    
@endsection

@section('before-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/global/scripts/datatable.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/datatables.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/pages/scripts/table-datatables-buttons.min.js") }}" type="text/javascript"></script>

@endsection

@section('scripts')
 
@endsection

resources/views/user/new.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
        <a href="{{ action('UserController@index') }}" class="nav-link nav-toggle">
            <span class="title">Usuários</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Criar
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Usuários
        <small>Criar</small>
    </h1>

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer bold"></i>
                    <span class="caption-subject bold uppercase">Criar Usuário</span>
                    <span class="caption-helper">formulário para criação de usuário</span>
                </div>
                <div class="actions">
                    
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ route('users.store') }}" METHOD="POST" id="formUser" class="form-horizontal" enctype="multipart/form-data">
                {{ csrf_field() }}
                    @include('user._form')
                </form>
                <!-- END FORM-->
            </div>
        </div>

    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')

@endsection

resources/views/user/profile.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
        <a href="#" class="nav-link nav-toggle">
            <span class="title">Usuários</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Alterar Senha
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Usuários
        <small>Editar</small>
    </h1>

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer bold"></i>
                    <span class="caption-subject bold uppercase">Alterar senha</span>
                    <span class="caption-helper">formulário para edição do usuário</span>
                </div>
                <div class="actions">
                    
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ route('users.update', Auth::user()->id) }}" METHOD="POST" id="formUser" class="form-horizontal" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="form-body">
                    <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button>
                    Você tem alguns erros de formulário. Por favor, verifique abaixo.
                    </div>
                    <div class="alert alert-success display-hide">
                    <button class="close" data-close="alert"></button> Sua validação de formulário foi bem sucedida! </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Nova Senha
                            <span class="required"> * </span></label>
                            <div class="col-md-5" data-toggle="popover" data-placement="top" data-content="Deve ter no mínimo 6 caracteres.">
                                <div class="input-icon right">
                                    <i class="fa fa-lock"></i>
                                    <input name="password" id="password" type="password" class="form-control" placeholder="Password"> 
                                    <span class="help-inline"> Deve ter no mínimo 6 caracteres. </span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Confirmar Senha
                            <span class="required"> * </span></label>
                            <div class="col-md-5" data-toggle="popover" data-placement="top" data-content="Deve ter no mínimo 6 caracteres.">
                                <div class="input-icon right">
                                    <i class="fa fa-lock"></i>
                                    <input name="password_confirm" name="password_confirm" type="password" class="form-control" placeholder="Password">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn btn-success">Salvar</button>
                                <a class="btn default" href="{{ route('home') }}">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>

    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')

@endsection