routes/web.php
<?php

use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::post('animals/foundAnimal', 'AnimalController@foundTheAnimal')->name('animals.foundAnimal');
Route::get('/register', 'UserController@register')->name('register');
Route::post('register/store', 'UserController@storeRegister')->name('storeRegister');

Route::group(['middleware' => 'auth'], function () {
	
	Route::resource('users', 'UserController');

    Route::resource('animals', 'AnimalController');
    Route::get('animals/showFinders/{animal}', 'AnimalController@showFinders')->name('animals.showFinders');
    
});

app/Animal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'picture', 
        'age',
        'note',
        'city',
        'state',
        'status_id',
        'user_id'
    ];

    /**
     * Get the status that owns the animal.
     */
    public function status()
    {
        return $this->belongsTo('App\StatusAnimal');
    }

    /**
     * Get the user that owns the animal.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     * Get the finders for the animal.
     */
    public function finders()
    {
        return $this->hasMany('App\Finder');
    }

}

app/Http/Controllers/AnimalController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Services\AnimalService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AnimalController extends Controller
{
    /**
     * Servico de Animais
     * @var \App\Services\AnimalService
     */
    protected $animalService;

    /**
     * Método construtor
     *
     * @param \App\Services\AnimalService  $animalService  O servico de animais
     */
    public function __construct(AnimalService $animalService)
    {
        $this->animalService = $animalService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = $this->animalService->findAnimalsByUser();

        return view('animals.index')->with(compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $animal = new \App\Animal();

        return view('animals.new')->with(compact('animal'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request = $this->animalService->fillRequestAnimal($request);

        $animal = $this->animalService->storeAnimal($request);

        // Create the animal
        if ( $animal ) {

            flash('Animal cadastrado com sucesso.');

        } else {
            flash()->error('Não foi possível cadastrar o animal. Contate o administrador.');
        }

        return redirect()->route('animals.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $animal = $this->animalService->findOrFailAnimal($id);

        return view('animals.edit', compact('animal'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, int $id)
    {
        $request = $this->animalService->fillRequestAnimal($request);
        
        if ($this->animalService->updateAnimal($request->all(), $id)) {
            flash()->success('Animal editado com sucesso.');
        } else {
            flash()->error('Não foi possível editar o Animal.');
        }

        return redirect()->route('animals.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        if ($this->animalService->destroyAnimal($id)) {
            flash()->success('Animal removido com sucesso');
        } else {
            flash()->success('Não foi possível remover o animal.');
        }

        return redirect()->route('animals.index');
    }

    /**
     * Método registra o comunicado de um animal
     *
     * @param      \Illuminate\Http\Request  $request  The request
     */
    public function foundTheAnimal(Request $request)
    {
        $finder = $this->animalService->storeFinder($request);

        $animal = $this->animalService->updateAnimal(['status_id' => 2], $request->input('animal_id'));

        if ($finder && $animal) {
            flash()->success('Comunicado enviado com sucesso');
        } else {
            flash()->success('Não foi possível efetuar o comunicado.');
        }

        return redirect()->route('home');
    }

    /**
     * Shows the finders.
     *
     * @param      integer  $id     The identifier
     *
     * @return     <type>   ( description_of_the_return_value )
     */
    public function showFinders(int $id)
    {
        $animal = $this->animalService->findOrFailAnimal($id);

        return view('animals.finders', compact('animal'));
    }
}

resources/views/animals/_form.blade.php
<div class="form-body">
    <div class="alert alert-danger display-hide">
    <button class="close" data-close="alert"></button>
    Você tem alguns erros de formulário. Por favor, verifique abaixo.
    </div>
    <div class="alert alert-success display-hide">
    <button class="close" data-close="alert"></button> Sua validação de formulário foi bem sucedida! </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Nome
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <div class="input-icon right">
                    <i class="fa fa-paw"></i>
                    <input name="name" type="text" class="form-control" placeholder="Nome do Animal" value="{{ old('name') ? old('name') : $animal->name }}"> </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Idade
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <div class="input-icon right">
                    <i class="fa fa-paw"></i>
                    <input name="age" type="text" class="form-control" placeholder="Idade do animal" value="{{ old('age') ? old('age') : $animal->age }}"> </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Informações Extras
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <textarea id="modal-note" name="note" class="form-control" rows="3">{{ old('city') ? old('city') : $animal->note }}
                </textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Cidade
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <div class="input-icon right">
                    <i class="fa fa-home"></i>
                    <input name="city" type="text" class="form-control" placeholder="Cidade do desaparecimento" value="{{ old('city') ? old('city') : $animal->city }}"> </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Estado
            <span class="required"> * </span></label>
            <div class="col-md-5">
                <div class="input-icon right">
                    <i class="fa fa-home"></i>
                    <input name="state" type="text" class="form-control" placeholder="EStado do desaparecimento" value="{{ old('state') ? old('state') : $animal->state }}"> </div>
            </div>
        </div>
        <div class="form-group ">
        <label class="control-label col-md-3">Foto</label>
        <div class="col-md-9">
            <div class="fileinput fileinput-new" data-provides="fileinput">
                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100%; height: 100px;"> </div>
                    <div>
                        <span class="btn red btn-outline btn-file">
                          <span class="fileinput-new"> Selecione a Imagen </span>
                          <span class="fileinput-exists"> Trocar </span>
                          <input type="file" name="attachmentTemp"> </span>
                        <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                    </div>
                </div>
            </div>
        </div>
</div>
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-3 col-md-9">
            <button type="submit" class="btn btn-success">Salvar</button>
            <a class="btn default" href="{{ route('animals.index') }}">Cancelar</a>
        </div>
    </div>
</div>

resources/views/animals/edit.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
    <li>
        <a href="{{ route('animals.index') }}" class="nav-link nav-toggle">
            <span class="title">Animais</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Editar
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Usuários
        <small>Editar</small>
    </h1>

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer bold"></i>
                    <span class="caption-subject bold uppercase">Editar Animal</span>
                    <span class="caption-helper">formulário para edição de animal</span>
                </div>
                <div class="actions">
                    
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ route('animals.update', $animal->id) }}" METHOD="POST" id="formUser" class="form-horizontal" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    @include('animals._form')
                </form>
                <!-- END FORM-->
            </div>
        </div>

    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')
    <script type="text/javascript">


    </script>
@endsection

resources/views/animals/finders.blade.php
@extends('layouts.default')

@section('title')
  Meus Animais
@endsection

@section('breadcumb')
	<li>
		Animais
	</li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Animais
        <small>Index</small>
    </h1>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">Comunicados do Animal</b></span>
                    </div>
                    <div class="tools">

                    </div>
                </div>
                <div class="portlet-body table-both-scroll">
                    <table class="table table-striped table-bordered table-hover order-column" id="">
                        <thead>
                            <tr>
                                <th>Foto</th>
                                <th>Nome</th>
                                <th>Telefone</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($animal->finders as $r)
                            <tr>
                                <td>
                                    <img class="img-responsive" style="width: 100px; height: 100px;" src="{{asset($animal->picture)}}">
                                </td>
                                <td>{{$r->name}}</td>
                                <td>{{$r->telefone}}</td>
                            </tr>
                        @endforeach    
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    
@endsection

@section('before-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/global/scripts/datatable.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/datatables.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js") }}" type="text/javascript"></script>

@endsection

@section('after-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/pages/scripts/table-datatables-buttons.min.js") }}" type="text/javascript"></script>


@endsection

@section('scripts')
 
@endsection

resources/views/animals/index.blade.php
@extends('layouts.default')

@section('title')
  Meus Animais
@endsection

@section('breadcumb')
	<li>
		Animais
	</li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Animais
        <small>Index</small>
    </h1>

	<a class="btn blue-sharp btn-outline sbold pull-right" href="{{ route('animals.create') }}"><i class="fa fa-paw"></i> Cadastrar Animal</a>
	<div style="margin:0; padding:0; height:50px;">&nbsp;</div>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">Meus Animais</b></span>
                    </div>
                    <div class="tools">

                    </div>
                </div>
                <div class="portlet-body table-both-scroll">
                    <table class="table table-striped table-bordered table-hover order-column" id="">
                        <thead>
                            <tr>
                                <th>Foto</th>
                                <th>Nome</th>
                                <th>Idade</th>
                                <th>Informações</th>
                                <th>Cidade</th>
                                <th>Estado</th>
                                <th>Status</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($result as $r)
                            <tr>
                                <td>
                                    <img class="img-responsive" style="width: 100px; height: 100px;" src="{{asset($r->picture)}}">
                                </td>
                                <td>{{$r->name}}</td>
                                <td>{{$r->age}}</td>
                                <td>{{$r->note}}</td>
                                <td>{{$r->city}}</td>
                                <td>{{$r->state}}</td>
                                <td>{{$r->status->description}}</td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs red dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Ações
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-left" role="menu">
                                            @if ($r->status_id === 2)
                                            <li>
                                                <a href="{{ route('animals.showFinders', $r->id) }}">
                                                    <i class="fa fa-edit"></i> Ver comunicados </a>
                                            </li>
                                            @endif
                                            <li>
                                                <a href="{{ route('animals.edit', $r->id) }}">
                                                    <i class="fa fa-edit"></i> Editar </a>
                                            </li>
                                            <li>
                                            <form role="form" action="{{ route('animals.destroy', $r->id) }}" METHOD="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}<button type="submit">Remover</button>
                                            </form>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        @endforeach    
                        </tbody>
                    </table>
                    {{ $result->appends($_GET)->links() }}
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    
@endsection

@section('before-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/global/scripts/datatable.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/datatables.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js") }}" type="text/javascript"></script>

@endsection

@section('after-plugins')
        <!--Datatable-->
        <script src="{{ asset("assets/pages/scripts/table-datatables-buttons.min.js") }}" type="text/javascript"></script>


@endsection

@section('scripts')
 
@endsection

resources/views/animals/new.blade.php
@extends('layouts.default')

@section('css-plugins')
        {{-- Select --}}
        <link href="{{ asset("assets/global/plugins/select2/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("assets/global/plugins/select2/css/select2-bootstrap.min.css") }}" rel="stylesheet" type="text/css" />

        {{-- File Input --}}
        <link href="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcumb')
	<li>
        <a href="{{ route('animals.index') }}" class="nav-link nav-toggle">
            <span class="title">Animais</span>
        </a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        Criar
    </li>
@endsection

@section('content')
	
    <h1 class="page-title">
    	Animais
        <small>Informar desaparecimento</small>
    </h1>

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer bold"></i>
                    <span class="caption-subject bold uppercase">Informar o desaparecimento de um animal</span>
                </div>
                <div class="actions">
                    
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ route('animals.store') }}" METHOD="POST" id="formAnimal" class="form-horizontal" enctype="multipart/form-data">
                {{ csrf_field() }}
                    @include('animals._form')
                </form>
                <!-- END FORM-->
            </div>
        </div>

    
@endsection

@section('before-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/global/plugins/select2/js/select2.full.min.js") }}" type="text/javascript"></script>

        {{-- Input File --}}
        <script src="{{ asset("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery.input-ip-address-control-1.0.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/jquery.validate.js") }}" type="text/javascript"></script>
        <script src="{{ asset("assets/global/plugins/jquery-validation/js/additional-methods.js") }}" type="text/javascript"></script>
@endsection

@section('after-plugins')
        {{-- Select --}}
        <script src="{{ asset("assets/pages/scripts/components-select2.min.js") }}" type="text/javascript"></script>

        {{-- Mask --}}
        <script src="{{ asset("assets/pages/scripts/form-input-mask.min.js") }}" type="text/javascript"></script>

        {{-- Validation --}}
        <script src="{{ asset("assets/pages/scripts/form-validation.js") }}" type="text/javascript"></script>
@endsection

@section('script')

@endsection